Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2018-10, with the labels that each got.

#1021 Create HoneyBot.yml
  _data/projects/HoneyBot.yml
Labels: needs tasks

#1025 Delete angular-formly.yml as it is archived
  _data/projects/angular-formly.yml
Labels: needs review

#1029 Adds algorithms-js as a project
  _data/projects/algorithms-js.yml
Labels: needs tasks

#1035 Add Saleor to available projects
  _data/projects/saleor.yml
Labels: needs tasks

#1023 Added Discourse
  _data/projects/Discourse.yml
Labels: needs review

#1026 Create cinema.yml
  _data/projects/cinema.yml
Labels: needs review

#1055 Adds EnumFP
  _data/projects/EnumFP.yml
Labels: needs tasks

#1014 Update contrast of footer text for a11y
  stylesheets/stylesheet.css
Labels: needs review

#1066 Add CFEngine
  _data/projects/cfengine.yml
Labels: needs tasks

#1067 Add Charcoal projects
  _data/projects/SmokeDetector.yml
  _data/projects/metasmoke.yml
Labels: needs work

#1072 Speed up build
  .travis.yml
Labels: needs review

#1056 Create WeebCodeNames.yml
  _data/projects/WeebCodeNames.yml
Labels: needs work
