Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2019-02, with the labels that each got.

#994 Improve website accessibility
  _includes/scripts.html
Labels: needs review

#956 open census projects: csharp, go, java, node, python, ruby
  _data/projects/opencensus-csharp.yml
  _data/projects/opencensus-go.yml
  _data/projects/opencensus-java.yml
  _data/projects/opencensus-node.yml
  _data/projects/opencensus-python.yml
  _data/projects/opencensus-ruby.yml
Labels: needs tasks

#1180 adding a project
  _data/projects/TeacherFund_Next.yml
Labels: needs work

#1181 Create Project16x16
  _data/projects/Project16x16.yml
Labels: needs work
