Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2019-10, with the labels that each got.

#1388 Introduce gnome-sound-recorder
  _data/projects/gnome-sound-recorder.yml
Labels: needs tasks

#1522 resolve "prefer-arrow-callback" in fetchIssueCount.js
  javascripts/fetchIssueCount.js
Labels: needs work

#1533 introduce some new and updated docs
  .github/CONTRIBUTING.md
  README.md
  docs/how-it-works.md
  package.json
Labels: needs review

#1559 Create TakeMeThere.yml
  _data/projects/TakeMeThere.yml
Labels: needs work

#1555 Create Blokaroka.yml
  _data/projects/Blokaroka.yml
Labels: needs work

#1588 more README cleanup and documentation refresh
  README.md
  docs/list-a-project.md
Labels: needs review

#1620 Create MangGym.yml
  _data/projects/MangGym.yml
Labels: needs tasks

#1626 Add Kwik to project list
  _data/projects/kwik.yml
Labels: needs work

#1653 Created OskiBot.yml
  _data/projects/OskiBot.yml
Labels: needs work
