Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2020-10, with the labels that each got.

#2326 Update SiMon Platform for Hacktoberfest 2020
  _data/projects/simon-quality.yml
Labels: needs work

#2387 Added my project fibonacci-series.yml
  _data/projects/fibonacci-series.yml
Labels: needs work

#2380 Create owasp-vulnerableapp.yml
  _data/projects/owasp-vulnerableapp.yml
Labels: needs work

#2379 adding devdojo tails project
  _data/projects/Devdojo_tails.yml
Labels: needs work

#2378 #2209 Show user when there is no matching results
  _includes/scripts.html
  javascripts/main.js
  stylesheets/stylesheet.css
Labels: discussion

#2401 added my new projects
  _data/projects/covid19app.yml
Labels: needs tasks
