Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2022-10, with the labels that each got.

#3423 Adding C-Dac-Notes Project
  _data/projects/c-dac-notes.yml
Labels: needs work

#3422 adding mocked-api project
  _data/projects/mocked-api.yml
Labels: needs work

#3421 Adding Python.Shiksha
  _data/projects/python-shiksha.yml
Labels: needs work

#3469 Small mistake is corrected
  README.md
Labels: hacktoberfest-accepted

#3461 added Dockerfile Archive project
  _data/projects/dockerfile-archieve.yml
Labels: needs tasks

#3481 added linkin project
  _data/projects/linkin.yml
Labels: needs tasks

#3470 adding my new project
  _data/projects/ieee-com-soc-new-project.yml
Labels: has questions

#3493 Add Bitwarden clients repository
  _data/projects/bitwarden-clients.yml
Labels: has questions

#3485 Create movie-quote-generator.yml
  _data/projects/movie-quote-generator.yml
Labels: needs tasks

#3503 Create Metadataremover.yml and add Metadata Removal Tool
  _data/projects/MetadataRemover.yml
Labels: needs work

#3501 Create pdftotext.yml to add pdftotext project
  _data/projects/pdftotext.yml
Labels: needs work

#3502 Create pqcrypt.yml add PQcrypt
  _data/projects/pqcrypt.yml
Labels: needs work

#3500 Create File-Analysis-Tool.yml and Add File Analysis Tool for Kali Linux
  _data/projects/File-Analysis-Tool.yml
Labels: needs work
