Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2024-12, with the labels that each got.

#4949 Create telemedecine-app.yml
  _data/projects/telemedecine-app.yml
Labels: needs work

#3526 Allow for dark mode toggling via keyboard
  _includes/header.html
  javascripts/dark-mode.js
  stylesheets/stylesheet.css
Labels: needs review

#4902 Move theme storing to local storage
  javascripts/dark-mode.js
Labels: needs-review

#4943 Consistent tags
  _includes/scripts.html
  stylesheets/stylesheet.css
Labels: needs-review
