Repository up-for-grabs/up-for-grabs.net, pull requests merged in 2024-11, with the labels that each got.

#4890 Added new project named Noted.
  _data/projects/noted.yml
Labels: needs work

#4810 Create GoldenATCTracking.yml
  _data/projects/GoldenATCTracking.yml
Labels: needs tasks

#4868 feat: add zero share project
  _data/projects/zero-share.yml
Labels: needs tasks

#4831 Adding despensa-web
  _data/projects/_data/projects/despensa-web.yml
Labels: needs review
